import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Getting Started',
      link: { type: 'generated-index', title: 'Getting Started' },
      items: [{ type: 'autogenerated', dirName: 'getting-started' }]
    },
    {
      type: 'category',
      label: 'MCP Tools',
      link: { type: 'generated-index', title: 'MCP Tools' },
      items: [{ type: 'autogenerated', dirName: 'mcp-tools' }]
    },
    {
      type: 'category',
      label: 'Extension',
      items: [{ type: 'autogenerated', dirName: 'extension' }]
    },
    {
      type: 'category',
      label: 'Security & Privacy',
      items: [{ type: 'autogenerated', dirName: 'security-privacy' }]
    },
    {
      type: 'category',
      label: 'Troubleshooting',
      items: [{ type: 'autogenerated', dirName: 'troubleshooting' }]
    },
    'faq',
    {
      type: 'category',
      label: 'Reference',
      items: [{ type: 'autogenerated', dirName: 'reference' }]
    }
  ]
};

export default sidebars;
