import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Getting Started',
      link: { type: 'generated-index', title: 'Getting Started' },
      items: [{ type: 'autogenerated', dirName: 'getting-started' }]
    },
    {
      type: 'category',
      label: 'Architecture',
      link: { type: 'generated-index', title: 'Architecture' },
      items: [{ type: 'autogenerated', dirName: 'architecture' }]
    },
    {
      type: 'category',
      label: 'MCP Tools',
      link: { type: 'generated-index', title: 'MCP Tools' },
      items: [{ type: 'autogenerated', dirName: 'mcp-tools' }]
    },
    {
      type: 'category',
      label: 'Extension',
      items: [{ type: 'autogenerated', dirName: 'extension' }]
    },
    {
      type: 'category',
      label: 'Server',
      items: [{ type: 'autogenerated', dirName: 'server' }]
    },
    {
      type: 'category',
      label: 'Security & Privacy',
      items: [{ type: 'autogenerated', dirName: 'security-privacy' }]
    },
    {
      type: 'category',
      label: 'Testing',
      items: [{ type: 'autogenerated', dirName: 'testing' }]
    },
    {
      type: 'category',
      label: 'Troubleshooting',
      items: [{ type: 'autogenerated', dirName: 'troubleshooting' }]
    },
    'faq',
    {
      type: 'category',
      label: 'Contributing',
      items: [{ type: 'autogenerated', dirName: 'contributing' }]
    },
    {
      type: 'category',
      label: 'Workflows',
      items: [{ type: 'autogenerated', dirName: 'workflows' }]
    },
    {
      type: 'category',
      label: 'Reference',
      items: [{ type: 'autogenerated', dirName: 'reference' }]
    }
  ]
};

export default sidebars;
